"""patient admitted_by admitted_at

Revision ID: 09517a5755e2
Revises: 9a7c99d3fb1c
Create Date: 2026-05-27 10:40:19.368201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09517a5755e2'
down_revision = '9a7c99d3fb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admitted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admitted_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            "fk_patients_admitted_by_users", "users", ["admitted_by"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint("fk_patients_admitted_by_users", type_='foreignkey')
        batch_op.drop_column('admitted_at')
        batch_op.drop_column('admitted_by')

    # ### end Alembic commands ###
