"""patient clinician_id

Revision ID: 9a7c99d3fb1c
Revises: ddcef7f70674
Create Date: 2026-05-27 10:28:16.812526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7c99d3fb1c'
down_revision = 'ddcef7f70674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinician_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_clinician_id'), ['clinician_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_patients_clinician_id_users", "users", ["clinician_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint("fk_patients_clinician_id_users", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patients_clinician_id'))
        batch_op.drop_column('clinician_id')

    # ### end Alembic commands ###
